AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM template for storage resources for a serverless API

Parameters:
  ApplicationName:
    Type: String
    Default: 'serverless-api'

Resources:
  
  CustomerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: CustomerId
          AttributeType: S
        - AttributeName: CreationDate
          AttributeType: S
        - AttributeName: Version
          AttributeType: N
        - AttributeName: Metadata
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: CustomerId
          KeyType: HASH
        - AttributeName: CreationDate
          KeyType: RANGE
      TableName: !Sub '${ApplicationName}-customer-table'
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  DynamoDB:
    Description: "DynamoDB table arn"
    Export:
      Name: !Join [ '-', [ !Ref ApplicationName, 'customer-table']]
    Value: !GetAtt CustomerTable.Arn